apiVersion: v1
kind: Service
metadata:
  name: scaleapp-service
  labels:
    app: scaleapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: scaleapp
