apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
    release: prometheus-operator
spec:
  endpoints:
    - interval: 10s
      targetPort: 8080
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: "scaleapp"