apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaleapp-hpa2
  labels:
    app: scaleapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaleapp-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: "http_requests_per_second"
        target:
          type: AverageValue
          averageValue: 50 